In [1]:
from keras.models import Sequential, load_model # type of model 
from keras.layers import Dense, Activation, Conv2D,MaxPooling2D, Dropout, Flatten
from keras.optimizers import sgd, Adadelta
from keras.datasets import mnist
from keras.losses import categorical_crossentropy
from keras.utils import to_categorical
import numpy as np

Using TensorFlow backend.


In [3]:
from google.colab import files
files.upload()

Saving LeNetTrainedAvgPoolSoftmax.h5 to LeNetTrainedAvgPoolSoftmax.h5


{'LeNetTrainedAvgPoolSoftmax.h5': b'\x89HDF\r\n\x1a\n\x00\x00\x00\x00\x00\x08\x08\x00\x04\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x80\x10\x01\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00`\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x88\x00\x00\x00\x00\x00\x00\x00\xa8\x02\x00\x00\x00\x00\x00\x00\x01\x00\x08\x00\x01\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00\x10\x00\x10\x00\x00\x00\x00\x00 \x03\x00\x00\x00\x00\x00\x00\x18\x01\x00\x00\x00\x00\x00\x00TREE\x00\x00\x01\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\

In [4]:
model = load_model('LeNetTrainedAvgPoolSoftmax.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [5]:
w=model.layers[0].get_weights()[0]
print (w.shape)
print(w[:,:,:,0].reshape((5,5)).T)
print(w[:,:,:,1].reshape((5,5)).T)
print(w[:,:,:,2].reshape((5,5)).T)
print(w[:,:,:,3].reshape((5,5)).T)
print(w[:,:,:,4].reshape((5,5)).T)
print(w[:,:,:,5].reshape((5,5)).T)


(5, 5, 1, 6)
[[-0.21613625 -0.07859628  0.3130845   0.12629654 -0.05459046]
 [-0.00196935  0.14516681  0.31135187 -0.18699132 -0.02070489]
 [ 0.11865747 -0.1344213  -0.32800493 -0.42198533  0.13627332]
 [ 0.10424704  0.40320876 -0.03240913 -0.14831091  0.16017126]
 [-0.41357574  0.12758726  0.01000263  0.05668884  0.10794638]]
[[ 0.009337   -0.11774833  0.05813945 -0.12161008 -0.11386234]
 [-0.21481858  0.06285805  0.21433245  0.30044436  0.03093307]
 [ 0.04858067  0.0105477   0.09961145  0.15883498 -0.14767532]
 [ 0.03868663 -0.04400511 -0.07091949  0.14448102  0.25653896]
 [-0.18455386 -0.09173399  0.1825036   0.09601179  0.05020696]]
[[ 0.02671904  0.05519391  0.13202704 -0.10285781 -0.04457979]
 [-0.13454738 -0.26110828  0.03485793 -0.04986131  0.20769024]
 [ 0.08258839  0.04976705  0.11938916 -0.09534641  0.09229124]
 [ 0.19240662 -0.09454737  0.05992815 -0.15330233 -0.24665995]
 [-0.05132896  0.04114397 -0.2196434   0.37776068 -0.01304007]]
[[ 2.2775795e-02  4.3411121e-01 -1.1883

In [6]:
N = 6
K = 5
L = 1
for l in range(0 , L):
  for k in range(0 , N):
    for j in range(0, K):
      for i in range(0, K):
        if (int(256*w[i,j,l,k])>=0):
          print ('{:032b}'.format(int(256*w[i,j,l,k])))
        else:
          print ('{:032b}'.format(4294967296+int(256*w[i,j,l,k])))

11111111111111111111111111001001
11111111111111111111111111101100
00000000000000000000000001010000
00000000000000000000000000100000
11111111111111111111111111110011
00000000000000000000000000000000
00000000000000000000000000100101
00000000000000000000000001001111
11111111111111111111111111010001
11111111111111111111111111111011
00000000000000000000000000011110
11111111111111111111111111011110
11111111111111111111111110101101
11111111111111111111111110010100
00000000000000000000000000100010
00000000000000000000000000011010
00000000000000000000000001100111
11111111111111111111111111111000
11111111111111111111111111011011
00000000000000000000000000101001
11111111111111111111111110010111
00000000000000000000000000100000
00000000000000000000000000000010
00000000000000000000000000001110
00000000000000000000000000011011
00000000000000000000000000000010
11111111111111111111111111100010
00000000000000000000000000001110
11111111111111111111111111100001
11111111111111111111111111100011
1111111111

In [7]:
w=256*model.layers[2].get_weights()[0]
print (w.shape)
print(w[:,:,0,0].reshape((5,5)).T)
print(w[:,:,1,0].reshape((5,5)).T)
print(w[:,:,2,0].reshape((5,5)).T)
print(w[:,:,3,0].reshape((5,5)).T)
print(w[:,:,4,0].reshape((5,5)).T)
print(w[:,:,5,0].reshape((5,5)).T)
print(w[:,:,0,1].reshape((5,5)).T)
print(w[:,:,1,1].reshape((5,5)).T)
print(w[:,:,2,1].reshape((5,5)).T)
print(w[:,:,3,1].reshape((5,5)).T)
print(w[:,:,4,1].reshape((5,5)).T)
print(w[:,:,5,1].reshape((5,5)).T)
print(w[:,:,0,2].reshape((5,5)).T)
print(w[:,:,1,2].reshape((5,5)).T)
print(w[:,:,2,2].reshape((5,5)).T)
print(w[:,:,3,2].reshape((5,5)).T)
print(w[:,:,4,2].reshape((5,5)).T)
print(w[:,:,5,2].reshape((5,5)).T)
print(w[:,:,0,3].reshape((5,5)).T)
print(w[:,:,1,3].reshape((5,5)).T)
print(w[:,:,2,3].reshape((5,5)).T)
print(w[:,:,3,3].reshape((5,5)).T)
print(w[:,:,4,3].reshape((5,5)).T)
print(w[:,:,5,3].reshape((5,5)).T)
print(w[:,:,0,4].reshape((5,5)).T)
print(w[:,:,1,4].reshape((5,5)).T)
print(w[:,:,2,4].reshape((5,5)).T)
print(w[:,:,3,4].reshape((5,5)).T)
print(w[:,:,4,4].reshape((5,5)).T)
print(w[:,:,5,4].reshape((5,5)).T)
print(w[:,:,0,5].reshape((5,5)).T)
print(w[:,:,1,5].reshape((5,5)).T)
print(w[:,:,2,5].reshape((5,5)).T)
print(w[:,:,3,5].reshape((5,5)).T)
print(w[:,:,4,5].reshape((5,5)).T)
print(w[:,:,5,5].reshape((5,5)).T)
print(w[:,:,0,6].reshape((5,5)).T)
print(w[:,:,1,6].reshape((5,5)).T)
print(w[:,:,2,6].reshape((5,5)).T)
print(w[:,:,3,6].reshape((5,5)).T)
print(w[:,:,4,6].reshape((5,5)).T)
print(w[:,:,5,6].reshape((5,5)).T)
print(w[:,:,0,7].reshape((5,5)).T)
print(w[:,:,1,7].reshape((5,5)).T)
print(w[:,:,2,7].reshape((5,5)).T)
print(w[:,:,3,7].reshape((5,5)).T)
print(w[:,:,4,7].reshape((5,5)).T)
print(w[:,:,5,7].reshape((5,5)).T)
print(w[:,:,0,8].reshape((5,5)).T)
print(w[:,:,1,8].reshape((5,5)).T)
print(w[:,:,2,8].reshape((5,5)).T)
print(w[:,:,3,8].reshape((5,5)).T)
print(w[:,:,4,8].reshape((5,5)).T)
print(w[:,:,5,8].reshape((5,5)).T)
print(w[:,:,0,9].reshape((5,5)).T)
print(w[:,:,1,9].reshape((5,5)).T)
print(w[:,:,2,9].reshape((5,5)).T)
print(w[:,:,3,9].reshape((5,5)).T)
print(w[:,:,4,9].reshape((5,5)).T)
print(w[:,:,5,9].reshape((5,5)).T)
print(w[:,:,0,10].reshape((5,5)).T)
print(w[:,:,1,10].reshape((5,5)).T)
print(w[:,:,2,10].reshape((5,5)).T)
print(w[:,:,3,10].reshape((5,5)).T)
print(w[:,:,4,10].reshape((5,5)).T)
print(w[:,:,5,10].reshape((5,5)).T)
print(w[:,:,0,11].reshape((5,5)).T)
print(w[:,:,1,11].reshape((5,5)).T)
print(w[:,:,2,11].reshape((5,5)).T)
print(w[:,:,3,11].reshape((5,5)).T)
print(w[:,:,4,11].reshape((5,5)).T)
print(w[:,:,5,11].reshape((5,5)).T)


(5, 5, 6, 12)
[[ 19.678707   -0.8774713  17.604366  -23.257385  -75.29933  ]
 [  5.508404  -26.665903    4.3632646  23.586218  -15.929089 ]
 [ 44.64206     8.230381  -36.846745   -1.832127  -62.452557 ]
 [-70.73349    -5.4449472 104.923935  -85.966354   42.38903  ]
 [110.06208   -93.72289    29.805115   57.644585  -26.051987 ]]
[[ -45.27984    -91.760445  -108.56459   -127.864204   -62.78583  ]
 [ -74.397      -63.125397  -114.66331    -87.927315  -116.87611  ]
 [  22.813936    -4.4385486  -41.767685   -76.070076  -221.29182  ]
 [  44.73395     -8.418628   -21.148897   -10.633819  -228.92838  ]
 [ -49.865     -102.2152    -119.550606   -71.73326   -195.35725  ]]
[[ 1.5940984e+02 -1.3885510e+00  3.2588497e+01  8.0837425e+01
  -1.0417691e+00]
 [ 4.8218155e+00 -6.2420994e+01  2.0372057e+01 -1.8827675e+01
   6.4835668e-02]
 [ 3.1832802e+01 -1.3419265e+01  6.2950371e+01 -5.6889004e+01
   1.9506826e+01]
 [ 2.0261187e+01 -4.0141411e+01  4.1827934e+01 -8.5047874e+00
  -4.8584164e+01]
 [-3.4834

In [8]:
N = 12
K = 5
L = 6
for l in range(0 , N):
  for k in range(0 , L):
    for j in range(0, K):
      for i in range(0, K):
        if (int(256*w[i,j,k,l])>=0):
          print ('{:032b}'.format(int(256*w[i,j,k,l])))
        else:
          print ('{:032b}'.format(4294967296+int(256*w[i,j,k,l])))

00000000000000000001001110101101
11111111111111111111111100100000
00000000000000000001000110011010
11111111111111111110100010111111
11111111111111111011010010110100
00000000000000000000010110000010
11111111111111111110010101010110
00000000000000000000010001011100
00000000000000000001011110010110
11111111111111111111000000010011
00000000000000000010110010100100
00000000000000000000100000111010
11111111111111111101101100101000
11111111111111111111111000101011
11111111111111111100000110001101
11111111111111111011100101000101
11111111111111111111101010001111
00000000000000000110100011101100
11111111111111111010101000001001
00000000000000000010101001100011
00000000000000000110111000001111
11111111111111111010001001000111
00000000000000000001110111001110
00000000000000000011100110100101
11111111111111111110010111110011
11111111111111111101001010111001
11111111111111111010010000111110
11111111111111111001001101110000
11111111111111111000000000100011
11111111111111111100000100110111
1111111111

In [11]:
w=model.layers[5].get_weights()[0]
np.set_printoptions(0,10000,150)
np.set_printoptions(suppress=True)
print((256*w))

[[ 254. 1088.  547.  335.  336.  315.  411.  489.  389.  275.]
 [  15.  719.  426.  671.    5.  128.  401.  360.  393.  290.]
 [  47. -180.   67.  142.   75.   89.  -51.  386.  285.  209.]
 [-145. -451. -348. -476. -186. -311. -264. -149. -214. -188.]
 [ 397.   93.  282.  376.  -90.  317.  309.  497.  318.  312.]
 [-317. -556. -214. -330. -796. -207. -240. -969. -295.  -50.]
 [  89.  525.   40.  -13.  246.  153.   90.  224.  370.  323.]
 [ 427.  299.  188.  369.   47.  349.  483.  381.   46.   88.]
 [ 379.  308.  570.  391.  512.  258.  433.  307.  399.  246.]
 [ 378.  577.  745.  836.  238.  120.  323.  660.  380.  306.]
 [ -60.  173. -429. -189. -282.  -26. -161. -106. -162.  -34.]
 [-385. -384.  -49.  219. -281. -573. -414.   -7. -269. -658.]
 [ 502.  368.  400.  278.  404.  155.  518.  341.  271.  339.]
 [ 298.  334.  485.  420.  330.  404.  368.  154.  464.  214.]
 [ -80. -241.  119.   48.    4.   92.   28.  220.   37.  124.]
 [-223.    7. -225. -220. -235. -442. -386.  -46. -372.

In [0]:
N = 192
L = 10
for i in range(0 , L):
  for j in range(0 , N):
    if (int(256*w[j,i])>=0):
      print ('{:032b}'.format(int(256*w[j,i])))
    else:
      print ('{:032b}'.format(4294967296+int(256*w[j,i])))


00000000000000000000000011111101
00000000000000000000000000001110
00000000000000000000000000101110
11111111111111111111111101110000
00000000000000000000000110001100
11111111111111111111111011000100
00000000000000000000000001011000
00000000000000000000000110101010
00000000000000000000000101111010
00000000000000000000000101111001
11111111111111111111111111000101
11111111111111111111111010000000
00000000000000000000000111110101
00000000000000000000000100101001
11111111111111111111111110110001
11111111111111111111111100100010
00000000000000000000000110010010
11111111111111111111111110000111
00000000000000000000000100100111
11111111111111111111111110001101
00000000000000000000000101110011
00000000000000000000000110010111
00000000000000000000000001110010
11111111111111111111111011110111
00000000000000000000001000100000
00000000000000000000000100101101
00000000000000000000000010001101
11111111111111111111111111100010
00000000000000000000000010010000
00000000000000000000000101110001
0000000000